Repository Azordev/maps-project, pull requests merged in 2022-03, with the labels that each got.

#85 Updated Experience View
  .gitignore
  cspell.json
  package-lock.json
  public/index.html
  src/assets/confirm-icon.svg
  src/assets/rating_img.svg
  src/assets/selected-star.svg
  src/assets/star.svg
  src/components/Modal/Modal.js
  src/components/Modal/Modal.styled.jsx
  src/components/Rating/Rating.styled.jsx
  src/pages/Confirm/Confirm.styled.jsx
  src/pages/Confirm/index.jsx
  src/styles/theme.js
Labels: Waiting review

#91 Added toast to show messages
  cspell.json
  package.json
  src/components/Form/Form.styled.jsx
  src/index.js
  src/pages/Check/index.jsx
  src/pages/Confirm/index.jsx
Labels: Waiting review

#84 Feat/#81 update application loading view
  src/assets/azordev-icon.png
  src/components/LoadingView/LoadingView.js
  src/components/LoadingView/LoadingView.styled.jsx
  src/components/LoadingView/index.js
  src/components/index.js
  src/index.js
Labels: Waiting review

#96 feat #89 check package code and return state
  cspell.json
  src/pages/Delivery/Delivery.layout.jsx
  src/pages/Delivery/index.jsx
Labels: Waiting review

#99 fix/#54 styles Home page
  public/index.html
  src/assets/delivery-guy.png
  src/assets/vehicle-delivery-guy.png
  src/pages/Home/Home.layout.jsx
  src/pages/Home/Home.styled.jsx
  src/pages/Home/index.jsx
Labels: Waiting review

#98 fix: image position on "Confirm" view
  src/layouts/Splitted.styled.jsx
  src/pages/Confirm/Confirm.styled.jsx
Labels: Waiting review

#101 fix/#100 height home images
  src/assets/delivery-man.png
  src/assets/logo.svg
  src/pages/Home/Home.styled.jsx
Labels: Waiting review

#102 fix actual eslint error #92
  .eslintrc.js
  src/styles/theme.js
Labels: Changes needed

#108 fix: linter issues
  .github/workflows/main.yaml
  README.md
  package.json
  src/App.js
  src/components/BackButton/BackButton.styled.jsx
  src/components/Form/Form.jsx
  src/components/LoadingView/LoadingView.styled.jsx
  src/components/Modal/Modal.js
  src/components/Modal/Modal.styled.jsx
  src/components/Rating/Rating.jsx
  src/components/Rating/Rating.styled.jsx
  src/const/la_center.js
  src/helpers/logError.js
  src/hooks/useChats.js
  src/hooks/useClientLocation.js
  src/hooks/useErrors.js
  src/hooks/usePackage.js
  src/hooks/useRates.js
  src/index.js
  src/layouts/ErrorBoundary.js
  src/layouts/Splitted.styled.jsx
  src/pages/Chat/Chat.styled.jsx
  src/pages/Chat/index.jsx
  src/pages/Check/Check.styled.jsx
  src/pages/Check/index.jsx
  src/pages/Confirm/Confirm.styled.jsx
  src/pages/Confirm/index.jsx
  src/pages/Delivery/Delivery.layout.jsx
  src/pages/Delivery/Delivery.styled.jsx
  src/pages/Delivery/index.jsx
  src/pages/Error/index.jsx
  src/pages/Home/Home.layout.jsx
  src/services/GraphQl/client.js
  src/styles/mixins.js
Labels: enhancement

#104 Feat/#80
  src/assets/spinner.png
  src/components/Modal/Modal.styled.jsx
  src/components/Spinner/Spinner.js
  src/components/Spinner/Spinner.styled.jsx
  src/components/Spinner/index.js
  src/pages/Delivery/Delivery.layout.jsx
  src/pages/Delivery/index.jsx
Labels: Waiting review

#105 fix/56: replace modal image and fix styles
  src/assets/send.png
  src/components/Modal/Modal.styled.jsx
  src/components/Text.jsx
  src/pages/Check/index.jsx
  src/pages/Delivery/index.jsx
  src/pages/NotFound/NotFound.layout.jsx
  src/styles/text.js
Labels: Waiting review
